version: "3.8"

services:
  telegate:
    image: armann7/telegate:latest
    pull_policy: always
    container_name: telegate
    user: "${USER_ID}:${GROUP_ID}"
    environment:
      BOT_TOKEN:
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 256M
        reservations:
          cpus: '0.25'
          memory: 64M
    ports:
      - "5000:5000"
    volumes:
      - ./data:/data
